---
name: install-packages
on: workflow_dispatch
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: updating environment
        run: echo "sudo apt update"
  install:
    runs-on: ubuntu-latest
    steps:
      - name: installing required packages
        run: echo "sudo apt install $package_name"
  enable:
    runs-on: ubuntu-latest
    steps:
      - name: enable the status of installed packages
        run: echo"sudo apt status $packages_name"
  staus_check:
    runs-on: ubuntu-latest
    steps:
      - name: checking the status of installed packages
        run: echo"apt systemctl status $installed_package"
  
  
